from app.exceptions.api import APIError


class AlreadyExistsError(APIError):
    pass
