from app.exceptions.api import APIError


class AlreadyInGameError(APIError):
    pass
